name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: LakshmikanthanC #${{ github.repository_owner }}
          background_color: "#0d1117"      # GitHub dark mode background
          grid_color: "#161b22"            # Slightly lighter for contrast
          pacman_color: "#facc15"          # Bright yellow
          ghost_color: "#f472b6"           # Pink ghost
          dot_color: "#ffffff"             # White dots
          eyes_color: "#000000"            # Black eye centers
          eye_background_color: "#ffffff"


      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
